config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#home'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/login/create', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  patch '/plans/:id/done', to: 'plans#done'
  resources :users
  resources :plans
end

app/models/application_record.rb
# frozen_string_literal: true

# 各モデルはApplicationRecordを継承する.
# 各モデルで共通的に行いたい処理をApplicationRecordに定義する.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/date_validator.rb
# frozen_string_literal: true

# 日付チェック用Validator(キャスト前の属性が渡ってくる想定)
class DateValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    Date.parse value if value.present?
  rescue ArgumentError, TypeError
    record.errors.add(attribute, I18n.t('errors.messages.invalid'))
  end
end

app/models/concerns/time_validator.rb
# frozen_string_literal: true

# 時刻チェック用Validator(キャスト前の属性が渡ってくる想定)
class TimeValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    Time.parse value if value.present?
  rescue ArgumentError, TypeError
    record.errors.add(attribute, I18n.t('errors.messages.invalid'))
  end
end

app/models/plan.rb
# frozen_string_literal: true

# plansテーブルに関するmodelファイル
class Plan < ApplicationRecord
  belongs_to :user
  before_save :all_day_time_nil, :actual_time_nil
  # done更新でないとき、バリデーションする
  with_options unless: :will_save_change_to_done? do
    # start_dateのvalidation
    validates :start_date_before_type_cast, presence: true, date: true
    # end_dateのvalidation
    validates :end_date_before_type_cast, presence: true, date: true
    # 終日でない時timeは必須
    with_options if: :not_all_day? do
      validates :start_time_before_type_cast, presence: true, time: true
      validates :end_time_before_type_cast, presence: true, time: true
    end
    # start_dateとend_dateの前後関係をvalidation
    validate :start_end_relation
  end
  # done更新のとき、バリデーションする
  with_options if: :will_save_change_to_done? do
    # doneがtrueの時、actual_timeのvalidation
    validates :actual_time_before_type_cast,
              numericality: { only_integer: true, greater_than_or_equal_to: 0 },
              allow_blank: false
  end

  private

  # start_dateとend_dateの前後関係をvalidation
  def start_end_relation
    return unless start_date && start_time && end_date && end_time

    start_datetime = DateTime.new(start_date.year, start_date.month, start_date.day,
                                  start_time.hour, start_time.min, start_time.sec)
    end_datetime = DateTime.new(end_date.year, end_date.month, end_date.day,
                                end_time.hour, end_time.min, end_time.sec)
    errors.add(:end_date, '終了日時は開始日時より後に設定してください') if start_datetime >= end_datetime
  end

  # 終日でないか判定
  def not_all_day?
    !all_day
  end

  # 終日の時は時刻をnilにする
  def all_day_time_nil
    self.start_time = nil if all_day
    self.end_time = nil if all_day
  end

  # doneがfalseならば、実績時間はnilにする
  def actual_time_nil
    self.actual_time = nil unless done
  end
end

app/models/user.rb
# frozen_string_literal: true

# usersテーブルに関するmodelファイル
class User < ApplicationRecord
  before_save :downcase_email
  has_many :plans, dependent: :destroy
  # name のvalidation
  validates(:name, presence: true)
  # email の validation
  VALID_EMAIL_REGEX = %r{\A[a-z\d]+[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z}i
  validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
  # passwordのvalidation セキュアなパスワード
  has_secure_password
  validates(:password, presence: true, length: { minimum: 6 }, allow_nil: true)

  private

  # メールアドレスを小文字に変更
  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  private

  # ログイン済みユーザーか確認する
  def logged_in_user
    redirect_to login_url unless logged_in?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home画面のcontroller
class HomeController < ApplicationController
  # Home画面
  def home
    @plans = current_user.plans.order(start_date: :asc, start_time: :asc) if logged_in?
  end
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

# 予定登録、編集処理のcontroller
class PlansController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit update destroy done]

  # 予定登録画面の初期表示
  def new
    @plan = Plan.new
  end

  # 予定登録処理
  def create
    @plan = current_user.plans.build(plan_params)
    if @plan.save
      flash[:info] = '予定を登録しました。'
      redirect_to @plan
    else
      render 'new'
    end
  end

  # 予定詳細画面
  def show
    @plan = Plan.find(params[:id])
  end

  # 予定編集 初期表示
  def edit
    @plan = Plan.find(params[:id])
  end

  # 予定更新
  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      flash[:success] = '予定を更新しました。'
      redirect_to @plan
    else
      render 'edit'
    end
  end

  # 予定削除
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:success] = '予定を削除しました。'
    redirect_to root_path
  end

  # 予定完了
  def done
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params_done)
      flash[:success] = '予定を完了しました。' if @plan.done
      redirect_to @plan
    else
      render 'show'
    end
  end

  private

  # パラメータの制限処理(登録、更新時)
  def plan_params
    params.require(:plan).permit(:title, :content, :all_day, :start_date, :start_time, :end_date, :end_time)
  end

  # パラメータの制限処理(完了更新時)
  def plan_params_done
    params.require(:plan).permit(:done, :actual_time)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# ログイン/ログアウト処理に関するcontroller
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user&.authenticate(params[:password])
      log_in(@user)
      redirect_to root_url
    else
      flash.now[:danger] = 'メールアドレスとパスワードが一致しません。'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User登録、編集処理のcontroller
class UsersController < ApplicationController
  before_action :correct_user,   only: %i[edit update]

  # ユーザー登録画面の初期表示
  def new
    @user = User.new
  end

  # ユーザー登録処理
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = 'ユーザー登録が完了しました。'
      log_in(@user)
      redirect_to root_url
    else
      render 'new'
    end
  end

  # ユーザー詳細画面
  def show
    @user = User.find(params[:id])
  end

  # User編集 初期表示
  def edit; end

  # User更新
  def update
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報を更新しました。'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  # パラメータの制限処理
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# 各helperはApplicationHelperを継承する.
# 各モデルで共通的に行いたい処理をApplicationHelperに定義する.
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# homeに関するhelper
module HomeHelper
end

app/helpers/plans_helper.rb
# frozen_string_literal: true

# Plansに関するヘルパー
module PlansHelper
  # title:nilの時に表示する文字列を返す
  def nil_title_convert(title)
    title.present? ? title : '(タイトルなし)'
  end

  # 時刻を加工して返す
  def time_format(time)
    if time.nil?
      ''
    elsif time.instance_of?(ActiveSupport::TimeWithZone)
      time.strftime('%H:%M')
    else
      begin
        Time.parse time if time.present?
      rescue ArgumentError, TypeError
        ''
      end
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

# ログイン/ログアウト処理に関するhelper
module SessionsHelper
  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ログイン中ユーザーを返す
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # 渡されたユーザーがカレントユーザーであればtrueを返す
  def current_user?(user)
    user && user == current_user
  end

  # ユーザーがログインしていればtrue、その他はfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # ユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.erb
<% if logged_in? %>
  <div>
    <p>ログイン済</p>
    <%= link_to '予定登録', new_plan_path %>
    <br><br>
    予定
    <script>
      function plan_del(id) {
        var form = document.createElement('form')
        form.action = '/plans/' + id;
        form.method = 'post';
        var method_input = document.createElement('input');
        method_input.setAttribute('name', '_method');
        method_input.setAttribute('value', 'delete');
        method_input.setAttribute('type', 'hidden');
        form.appendChild(method_input);
        document.body.appendChild(form);
        form.submit();
      }
    </script>
    <ul>
      <% @plans.each do |plan| %>
        <li>
          <%= link_to nil_title_convert(plan.title), plan %>
          <%=
            button_tag '編集', type: 'button', onclick: "location.href='#{edit_plan_path(plan)}'"
          %>
          <%=
            button_tag '削除', type: 'button', onclick: "plan_del(#{plan.id})"
          %>
        </li>
        <ul>
          <li>
            <% if plan.all_day %>
              <%= plan.start_date.strftime('%Y/%m/%d') %> - <%= plan.end_date.strftime('%Y/%m/%d') %> (終日)
            <% else %>
              <%= plan.start_date.strftime('%Y/%m/%d') %> <%= plan.start_time.strftime('%H:%M') %>
              -
              <%= plan.end_date.strftime('%Y/%m/%d') %> <%= plan.end_time.strftime('%H:%M') %>
            <% end %>
          </li>
        </ul>
      <% end %>
    </ul>
  </div>
<% else %>
  <div>
    <p>boosterを利用しよう！</p>
    <%= link_to '新規登録', signup_path %>
    <%= link_to 'todoゲストログイン', root_path %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<br>
<b>
  <%= link_to 'booster', root_path %>
</b>
<% if logged_in? %>
  <%= link_to 'プロフィール', current_user %>
  <%= link_to 'ログアウト', logout_path %>
<% else %>
  <%= link_to 'ログイン', login_path %>
  <%= link_to '新規登録', signup_path %>
  <%= link_to 'ゲストログインtodo', root_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>booster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}")%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with model: @plan, url: yield(:form_url), method: yield(:method) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title, 'タイトル' %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :content, '内容' %>
    <%= f.text_area :content, class: 'form-control' %>
    <br>
    <%= f.label :all_day, '終日' %>
    <%= f.check_box :all_day, class: 'form-control' %>
    <br>
    <%= f.label :start_date, '開始日時' %>
    <%= f.text_field :start_date, type: 'date', class: 'form-control' %>
    <%= f.text_field :start_time, type: 'time', class: 'form-control', 
        value: time_format(f.object.start_time)
    %>
    <br>
    <%= f.label :end_date, '終了日時' %>
    <%= f.text_field :end_date, type: 'date', class: 'form-control' %>
    <%= f.text_field :end_time, type: 'time', class: 'form-control', 
        value: time_format(f.object.end_time)
    %>
    <br>
    <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/plans/edit.html.erb
<% provide(:form_url, "/plans/#{@plan.id}/") %>
<% provide(:method, 'patch')%>
<% provide(:button_text, '更新')%>
<h1>予定編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/plans/new.html.erb
<% provide(:form_url, '/plans/') %>
<% provide(:method, 'post')%>
<% provide(:button_text, '登録')%>
<h1>予定登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/plans/show.html.erb
<h1>予定詳細</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    タイトル:<%= @plan.title %><br>
    内容:<%= @plan.content %><br>
    日時:   
      <% if @plan.all_day %>
        <%= @plan.start_date.strftime('%Y/%m/%d') %> - <%= @plan.end_date.strftime('%Y/%m/%d') %> (終日)
      <% else %>
        <%= @plan.start_date.strftime('%Y/%m/%d') %> <%= @plan.start_time.strftime('%H:%M') %>
        -
        <%= @plan.end_date.strftime('%Y/%m/%d') %> <%= @plan.end_time.strftime('%H:%M') %>
      <% end %><br>
  </div>
  <%= link_to '編集', edit_plan_path %><br>
  <%= form_with model: @plan, url: "/plans/#{@plan.id}/done", method: 'patch' do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :done, '完了済み' %>
    <%= f.check_box :done, class: 'form-control' %>
    <br>
    <%= f.label :actual_time, '実績時間' %>
    <%= f.text_field :actual_time, type: 'number', class: 'form-control' %>
    <br>
    <%= f.submit '完了更新', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, url: yield(:form_url), method: yield(:method) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
    <br>
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
    <br>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
    <br>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <br>
    <%= f.submit yield(:button_text), class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<% provide(:form_url, "/users/#{@user.id}/") %>
<% provide(:method, 'patch')%>
<% provide(:button_text, '更新')%>
<h1>ユーザー更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:form_url, 'signup') %>
<% provide(:method, 'post')%>
<% provide(:button_text, '登録')%>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    ユーザー名:<%= @user.name %>
  </div>
  <%= link_to '編集', edit_user_path %>
</div>